const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE={schedule:'batanesScheduleV4',plan:'batanesPlanV4',memories:'batanesMemoriesV4'};
const heroSlides=[
 {title:'Batanes',overline:'THE NORTHERNMOST ISLANDS',text:'A quiet archipelago of rolling hills, stone villages and dramatic coastlines at the northern edge of the Philippines.',image:'assets/images/hero-batanes.jpg',zone:'north'},
 {title:'North Batan',overline:'LIGHTHOUSES · HILLS · BASCO',text:'Start around Basco, then follow the coast toward Naidi, Valugan and the open ridges of northern Batan Island.',image:'assets/images/hero-north-batan.jpg',zone:'north'},
 {title:'Sabtang',overline:'STONE VILLAGES · SEA CROSSING',text:'Cross from Ivana and discover villages, cliffs and cultural landscapes that reward a slower day.',image:'assets/images/hero-sabtang.jpg',zone:'sabtang'},
 {title:'South Batan',overline:'PASTURES · HERITAGE · COAST',text:'Move through Mahatao, Ivana and Uyugan for broad pastures, old houses and layered coastal scenery.',image:'assets/images/hero-south-batan.jpg',zone:'south'}
];
const zones={
 north:{no:'01',label:'NORTH BATAN',title:'North Batan',desc:'Basco is the natural starting point: lighthouse views, boulder coastline, rolling hills and easy access to the northern side of Batan Island.',image:heroSlides[1].image,meta:['Basco base','Half-day friendly','Coast + hills'],center:[20.4487,121.9702],places:[
  {id:'basco-lighthouse',name:'Basco Lighthouse',area:'North Batan',img:'assets/images/basco-lighthouse.jpg',text:'A landmark above Naidi Hills with broad views around Basco and the surrounding coast.',tags:['Lighthouse','Viewpoint'],lat:20.459,lng:121.969},
  {id:'valugan',name:'Valugan Boulder Beach',area:'North Batan',img:'assets/images/valugan-boulder-beach.jpg',text:'A dramatic shoreline known for rounded volcanic boulders and powerful surf.',tags:['Coast','Photography'],lat:20.465,lng:121.994},
  {id:'vayang',name:'Vayang Rolling Hills',area:'North Batan',img:'assets/images/vayang-rolling-hills.jpg',text:'Open green ridges and sweeping views that capture the windswept character associated with Batanes.',tags:['Hills','Landscape'],lat:20.475,lng:121.963}]},
 south:{no:'02',label:'SOUTH BATAN',title:'South Batan',desc:'A full-day route through Mahatao, Ivana and Uyugan, where pasture, heritage architecture and coastal viewpoints unfold one after another.',image:heroSlides[3].image,meta:['Full-day route','Heritage + pasture','Mahatao to Uyugan'],center:[20.35,121.94],places:[
  {id:'rakuh',name:'Rakuh a Payaman',area:'South Batan',img:'assets/images/rakuh-a-payaman.jpg',text:'Expansive pastureland and sea views often associated with the pastoral landscape of Batanes.',tags:['Pasture','Viewpoint'],lat:20.371,lng:121.971},
  {id:'tayid',name:'Tayid Lighthouse',area:'South Batan',img:'assets/images/tayid-lighthouse.jpg',text:'A lighthouse viewpoint in Mahatao with a different perspective across the eastern side of Batan Island.',tags:['Lighthouse','Coast'],lat:20.407,lng:121.963},
  {id:'dakay',name:'House of Dakay',area:'South Batan',img:'assets/images/house-of-dakay.jpg',text:'A heritage stone house that helps visitors understand traditional Ivatan architecture.',tags:['Heritage','Architecture'],lat:20.371,lng:121.915}]},
 sabtang:{no:'03',label:'SABTANG ISLAND',title:'Sabtang',desc:'A sea crossing leads to stone villages, dramatic viewpoints and a cultural landscape that deserves an unhurried full day.',image:'assets/images/chavayan-village.jpg',meta:['Via Ivana Port','Full-day trip','Villages + cliffs'],center:[20.33,121.87],places:[
  {id:'chavayan',name:'Chavayan Village',area:'Sabtang',img:'assets/images/chavayan-village.jpg',text:'A traditional village known for stone houses and a strong sense of Ivatan built heritage.',tags:['Village','Heritage'],lat:20.303,lng:121.869},
  {id:'chamantad',name:'Chamantad–Tiñan',area:'Sabtang',img:'assets/images/chamantad-tinan.jpg',text:'A dramatic viewpoint where rolling terrain meets the sea.',tags:['Viewpoint','Landscape'],lat:20.315,lng:121.877},
  {id:'morong',name:'Morong Beach',area:'Sabtang',img:'assets/images/morong-beach.jpg',text:'A coastal stop associated with the recognizable Ahaw natural arch and Sabtang scenery.',tags:['Beach','Natural arch'],lat:20.345,lng:121.873}]},
 itbayat:{no:'04',label:'ITBAYAT ISLAND',title:'Itbayat',desc:'The northern inhabited island offers a more remote experience. Treat schedules and sea conditions as part of the journey, not an inconvenience.',image:'assets/images/hero-itbayat.jpg',meta:['Remote island','Weather-dependent','Plan extra time'],center:[20.78,121.84],places:[
  {id:'itbayat-town',name:'Itbayat Town',area:'Itbayat',img:'assets/images/itbayat-town.jpg',text:'The island community is a base for understanding Itbayat life and its distinctive setting.',tags:['Community','Culture'],lat:20.787,lng:121.842},
  {id:'torongan',name:'Torongan Cave Area',area:'Itbayat',img:'assets/images/torongan-cave.jpg',text:'A natural and cultural landscape that should be visited with current local guidance.',tags:['Nature','Local guide'],lat:20.803,lng:121.855}]}
};
const experiences=[
 {type:'CULTURE',title:'Walk through Ivatan heritage',text:'Slow down in villages and look beyond the stone walls. Architecture and everyday routines make more sense when treated as living culture rather than scenery.',tags:['Stone houses','Villages','Respectful travel'],photos:[zones.sabtang.places[0].img,'assets/images/ivatan-heritage.jpg',zones.south.places[2].img]},
 {type:'FOOD',title:'Taste the islands deliberately',text:'Ivatan cooking reflects preservation, farming and island life. Look for luñis, uved, vunes, dibang and turmeric rice when available, and ask how each is prepared.',tags:['Luñis','Uved','Vunes','Dibang'],photos:['assets/images/food-lunis.jpg','assets/images/food-uved.jpg','assets/images/food-dibang.jpg']},
 {type:'LANDSCAPE',title:'Follow the wind across the hills',text:'Open ridges and pastures are best experienced without rushing from one photo stop to another. Give the landscape time to change with the light.',tags:['Rolling hills','Photography','Walking'],photos:[zones.north.places[2].img,zones.south.places[0].img,'assets/images/hero-batanes.jpg']},
 {type:'COAST',title:'Read the islands from the shore',text:'Boulder beaches, cliffs and sea crossings reveal how strongly Batanes is connected to the water. Conditions can change quickly, so local guidance matters.',tags:['Coast','Sea','Weather'],photos:[zones.north.places[1].img,zones.sabtang.places[2].img,'assets/images/coast-sabtang.jpg']},
 {type:'JOURNEY',title:'Cross to Sabtang with time to spare',text:'The crossing is part of the experience. Build flexibility around the day and avoid tight connections when weather can affect sea travel.',tags:['Sabtang','Ivana Port','Flexible plan'],photos:[zones.sabtang.places[2].img,zones.sabtang.places[0].img,'assets/images/coast-sabtang.jpg']}
];
const gallery=[['assets/images/gallery-01.jpg','landscape','Vayang Rolling Hills'],['assets/images/gallery-02.jpg','coast','Valugan Boulder Beach'],['assets/images/gallery-03.jpg','culture','Chavayan heritage'],['assets/images/gallery-04.jpg','landscape','Rakuh a Payaman'],['assets/images/gallery-05.jpg','culture','Ivatan life'],['assets/images/gallery-06.jpg','coast','Morong Beach'],['assets/images/gallery-07.jpg','landscape','Tayid Lighthouse'],['assets/images/gallery-08.jpg','culture','Basco Lighthouse']];
const foodCards=[['LUÑIS','Preserved Ivatan pork','A preservation-focused pork dish associated with Ivatan food traditions.','assets/images/food-lunis.jpg'],['UVED / UVUD','Banana-corm dish','A local preparation commonly described with grated banana corm and meat or fish.','assets/images/food-uved.jpg'],['VUNES','Dried taro stalks','A vegetable preparation tied to local crops and preservation.','assets/images/food-vunes.jpg'],['DIBANG','Flying fish','A seasonal island fish commonly associated with Batanes cuisine.','assets/images/food-dibang.jpg'],['TURMERIC RICE','Yellow rice','Rice prepared with turmeric, often encountered alongside local meals.','assets/images/food-turmeric-rice.jpg']];
const areaFlows={north:['Basco arrival','North Batan loop','South Batan day','Flexible / revisit'],south:['Basco arrival','South Batan loop','North Batan day','Flexible / revisit'],sabtang:['Basco arrival','North or South Batan','Sabtang day trip','Weather buffer'],itbayat:['Basco arrival','Batan Island day','Prepare for Itbayat','Itbayat / buffer day']};
let schedule=JSON.parse(localStorage.getItem(STORE.schedule)||'[]');
let memories=JSON.parse(localStorage.getItem(STORE.memories)||'[]');
let state={view:'home',hero:0,zone:'north',experience:0,experiencePhoto:0,plannerStep:1,area:'north',modalItem:null,editingId:null,pendingMemory:null};
let map,tripMap,heroTimer;
function safe(t=''){return String(t).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function allPlaces(){return Object.values(zones).flatMap(z=>z.places)}
function getPlan(){try{return JSON.parse(localStorage.getItem(STORE.plan)||'null')}catch{return null}}
function daysCount(){return Math.max(1,getPlan()?.days||4)}
function money(n){return '₱'+Math.round(+n||0).toLocaleString('en-PH')}
function showToast(t){$('#toastNote span').textContent=t;$('#toastNote').classList.add('show');setTimeout(()=>$('#toastNote').classList.remove('show'),2200)}
function navigate(name){const target=$(`.view[data-page="${name}"]`);if(!target)return;$$('.view').forEach(v=>v.classList.toggle('active',v===target));$$('.desktop-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));state.view=name;$('#siteHeader').classList.toggle('light',['guide','itinerary','gallery','experiences'].includes(name));$('#mobileMenu').classList.remove('open');target.scrollTop=0;if(name==='discover')setTimeout(()=>map?.invalidateSize(),150);if(name==='itinerary')renderItinerary();}
function renderHero(){const h=heroSlides[state.hero];$('#heroBg').style.backgroundImage=`url('${h.image}')`;$('#heroTitle').textContent=h.title;$('#heroOverline').textContent=h.overline;$('#heroText').textContent=h.text;$('#heroIndex').textContent=String(state.hero+1).padStart(2,'0');$('#heroProgress').style.width=((state.hero+1)/heroSlides.length*100)+'%';$('#heroDeck').innerHTML=heroSlides.map((x,i)=>`<button class="hero-card ${i===state.hero?'active':''}" data-hero="${i}" style="background-image:url('${x.image}')"><span>${String(i+1).padStart(2,'0')}</span><b>${x.title}</b><small>${x.overline.split(' · ').slice(0,2).join(' · ')}</small></button>`).join('');$$('[data-hero]').forEach(b=>b.onclick=()=>{state.hero=+b.dataset.hero;renderHero();restartHero()})}
function restartHero(){clearInterval(heroTimer);heroTimer=setInterval(()=>{if(state.view==='home'){state.hero=(state.hero+1)%heroSlides.length;renderHero()}},7000)}
function renderHomeExtras(){ $('#homeIslandGrid').innerHTML=Object.entries(zones).map(([k,z])=>`<button data-home-zone="${k}" style="background-image:url('${z.image}')"><span>${z.no}</span><div><small>${z.label}</small><b>${z.title}</b></div><i class="bi bi-arrow-up-right"></i></button>`).join('');$$('[data-home-zone]').forEach(b=>b.onclick=()=>{state.zone=b.dataset.homeZone;renderZone();navigate('discover')});const picks=[zones.north.places[2],zones.south.places[0],zones.sabtang.places[0],zones.north.places[1]];$('#homePlaceRail').innerHTML=picks.map(p=>`<article style="background-image:url('${p.img}')"><div><small>${p.area}</small><h4>${p.name}</h4><button data-home-place="${p.id}">View place <i class="bi bi-arrow-right"></i></button></div></article>`).join('');$$('[data-home-place]').forEach(b=>b.onclick=()=>openDetail(allPlaces().find(p=>p.id===b.dataset.homePlace)))}
function renderZone(){const z=zones[state.zone];$('#zoneBackdrop').style.backgroundImage=`url('${z.image}')`;$('#zoneNo').textContent=z.no;$('#zoneLabel').textContent=z.label;$('#zoneTitle').textContent=z.title;$('#zoneDesc').textContent=z.desc;$('#zoneMeta').innerHTML=z.meta.map(x=>`<span>${x}</span>`).join('');$('#zoneTabs').innerHTML=Object.entries(zones).map(([k,x])=>`<button class="zone-tab ${k===state.zone?'active':''}" data-zone="${k}"><span>${x.no}</span><b>${x.title}</b><i class="bi bi-arrow-right"></i></button>`).join('');$('#placeStrip').innerHTML=z.places.map(p=>`<button class="place-card" data-place="${p.id}" style="background-image:url('${p.img}')"><span>${p.area}</span><b>${p.name}</b><i class="bi bi-arrow-up-right"></i></button>`).join('');$$('[data-zone]').forEach(b=>b.onclick=()=>{state.zone=b.dataset.zone;renderZone();focusMapZone()});$$('[data-place]').forEach(b=>b.onclick=()=>openDetail(allPlaces().find(p=>p.id===b.dataset.place)))}
function openDetail(item){if(!item)return;state.modalItem={...item,type:'place'};$('#detailMedia').style.backgroundImage=`url('${item.img}')`;$('#detailArea').textContent=item.area;$('#detailTitle').textContent=item.name;$('#detailText').textContent=item.text;$('#detailTags').innerHTML=item.tags.map(t=>`<span>${t}</span>`).join('');$('#detailModal').classList.add('open')}
function renderExperience(){const e=experiences[state.experience];state.experiencePhoto=Math.min(state.experiencePhoto,e.photos.length-1);$('#experienceNo').textContent=String(state.experience+1).padStart(2,'0');$('#experienceType').textContent=e.type;$('#experienceTitle').textContent=e.title;$('#experienceText').textContent=e.text;$('#experienceTags').innerHTML=e.tags.map(t=>`<span>${t}</span>`).join('');$('#experiencePhotoTrack').innerHTML=e.photos.map((src,i)=>`<figure class="${i===state.experiencePhoto?'active':''}" style="background-image:url('${src}')"></figure>`).join('');$('#experiencePhotoCounter').textContent=`${String(state.experiencePhoto+1).padStart(2,'0')} / ${String(e.photos.length).padStart(2,'0')}`;$('#experienceTabs').innerHTML=experiences.map((x,i)=>`<button class="experience-tab ${i===state.experience?'active':''}" data-exp="${i}"><span>0${i+1}</span><b>${x.type}</b></button>`).join('');$$('[data-exp]').forEach(b=>b.onclick=()=>{state.experience=+b.dataset.exp;state.experiencePhoto=0;renderExperience()})}
function moveExperiencePhoto(dir){const e=experiences[state.experience];state.experiencePhoto=(state.experiencePhoto+dir+e.photos.length)%e.photos.length;renderExperience()}
function guideHtml(key){
 if(key==='location')return `<div class="guide-modal-grid"><div class="guide-modal-copy"><span class="micro-label">LOCATION</span><h2>At the northern edge of the Philippines.</h2><p>Batanes is an island province in the Cagayan Valley region. Batan Island holds Basco, while Sabtang and Itbayat extend the journey beyond the main visitor base.</p><div class="row g-3 mt-3"><div class="col-6"><div class="guide-fact"><small>MAIN BASE</small><b>Basco, Batan Island</b></div></div><div class="col-6"><div class="guide-fact"><small>ISLAND AREAS</small><b>Batan · Sabtang · Itbayat</b></div></div></div><button class="btn-main dark-btn mt-4" id="guideOpenMap"><i class="bi bi-map"></i> Open full interactive map</button></div><div class="guide-modal-map" id="guideMiniMap"></div></div>`;
 if(key==='people')return `<div class="guide-modal-grid"><img class="guide-modal-image img-fluid" src="assets/images/culture-stone-houses.jpg" alt="Ivatan stone houses"><div class="guide-modal-copy"><span class="micro-label">PEOPLE & CULTURE</span><h2>The Ivatan story behind the landscape.</h2><p>Ivatan identity is visible in language, village life, food traditions and stone architecture adapted to an exposed island environment. Homes and communities are living places, not photo props.</p><div class="guide-list"><span><i class="bi bi-house-heart"></i><b>Stone-house heritage</b><small>Architecture shaped by local materials and climate.</small></span><span><i class="bi bi-camera"></i><b>Respectful photography</b><small>Ask before photographing residents and private homes.</small></span><span><i class="bi bi-people"></i><b>Living culture</b><small>Look beyond landmarks and notice everyday island life.</small></span></div></div></div>`;
 if(key==='getting')return `<div class="guide-modal-grid"><img class="guide-modal-image img-fluid" src="assets/images/basco-airport.jpg" alt="Basco Airport"><div class="guide-modal-copy"><span class="micro-label">GETTING THERE / BASCO</span><h2>Basco is the practical starting point.</h2><p>Basco Airport is the usual air gateway. Airfare changes by date and airline, so use a current quote instead of relying on an old fixed fare.</p><div class="fare-box mt-4"><label class="form-label">Possible round-trip airfare / person</label><div class="input-group input-group-lg"><span class="input-group-text">₱</span><input id="guideFare" type="number" min="0" step="1" class="form-control" placeholder="Enter current quote"></div><small>This syncs with the trip planner as a working estimate.</small></div></div></div>`;
 if(key==='season')return `<div class="guide-modal-copy full"><span class="micro-label">BEST TIME / WHY IT MATTERS</span><h2>Choose the season for the kind of trip you want.</h2><div class="season-grid mt-4"><article><b>MAR–MAY</b><span>Often preferred for sightseeing</span><p>Usually easier for outdoor planning and landscape-heavy itineraries, while current forecasts still matter.</p><small>GOOD FOR · first visits · outdoor days</small></article><article><b>JUN–NOV</b><span>More weather-sensitive</span><p>Rain and tropical weather can disrupt flights or sea crossings. Build more buffer into the itinerary.</p><small>GOOD FOR · flexible travelers</small></article><article><b>DEC–FEB</b><span>Cooler & windier feel</span><p>Cooler conditions can be appealing, but strong winds may still affect sea plans and exposed viewpoints.</p><small>GOOD FOR · cool-weather scenery</small></article></div></div>`;
 if(key==='tips')return `<div class="guide-modal-copy full"><span class="micro-label">LOCAL TIPS</span><h2>Travel slower than your checklist.</h2><div class="row g-3 mt-3"><div class="col-md-6"><div class="tip-card"><i class="bi bi-people"></i><b>Community</b><p>Ask before photographing residents or private homes.</p></div></div><div class="col-md-6"><div class="tip-card"><i class="bi bi-wallet2"></i><b>Money</b><p>Keep some cash available for smaller local expenses.</p></div></div><div class="col-md-6"><div class="tip-card"><i class="bi bi-cloud-wind"></i><b>Weather</b><p>Leave buffer time around flights and sea crossings.</p></div></div><div class="col-md-6"><div class="tip-card"><i class="bi bi-signpost"></i><b>Heritage</b><p>Follow local site rules and avoid treating communities as sets.</p></div></div></div></div>`;
 return `<div class="guide-modal-copy full"><span class="micro-label">TASTE OF BATANES</span><h2>Food is part of the cultural story.</h2><p>Browse dishes connected to preservation, farming, fishing and island life.</p><div class="food-rail mt-4">${foodCards.map(f=>`<article><img src="${f[3]}" class="img-fluid" alt="${f[0]}"><small>MUST TRY</small><b>${f[0]}</b><span>${f[1]}</span><p>${f[2]}</p></article>`).join('')}</div></div>`
}
function openGuideDetail(key){
 $('#guideDetailBody').innerHTML=guideHtml(key);
 const modal=bootstrap.Modal.getOrCreateInstance($('#guideDetailModal'));
 modal.show();
 if(key==='location')setTimeout(()=>{const el=$('#guideMiniMap');if(!el||el.dataset.ready)return;el.dataset.ready='1';const m=L.map(el,{zoomControl:true,attributionControl:false}).setView([20.45,121.95],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18}).addTo(m);Object.values(zones).forEach(z=>L.circleMarker(z.center,{radius:7}).addTo(m).bindTooltip(z.title));$('#guideOpenMap').onclick=()=>{modal.hide();openMap()}},250);
 if(key==='getting'&&$('#guideFare')){$('#guideFare').value=$('#airfare')?.value||'';$('#guideFare').oninput=e=>{$('#airfare').value=e.target.value;updatePlannerSummary()}}
}
function renderGuide(){ /* Guide topics are explicit Bootstrap cards in HTML. */ }
function initMap(){if(!window.L)return;map=L.map('map').setView([20.45,121.95],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);allPlaces().forEach(p=>{if(!p.lat)return;L.marker([p.lat,p.lng]).addTo(map).on('click',()=>{$('#mapInfo').innerHTML=`<span>${safe(p.area)}</span><h4>${safe(p.name)}</h4><p>${safe(p.text)}</p><button class="btn-main dark-btn" data-map-schedule="${p.id}">Add to itinerary</button>`;$('#mapInfo [data-map-schedule]').onclick=()=>openScheduler({...p,type:'place'})})})}
function openMap(){state.view='discover';navigate('discover');$('#mapDrawer').classList.add('open');setTimeout(()=>map?.invalidateSize(),300)}
function focusMapZone(){if(map){map.flyTo(zones[state.zone].center,state.zone==='itbayat'?10:11,{duration:.7})}}
function renderAreaChoices(){$('#areaChoices').innerHTML=Object.entries(zones).map(([k,z])=>`<button type="button" class="area-choice ${k===state.area?'active':''}" data-area="${k}"><small>${z.no} / ${z.label}</small><b>${z.title}</b></button>`).join('');$$('[data-area]').forEach(b=>b.onclick=()=>{state.area=b.dataset.area;renderAreaChoices();updatePlannerSummary()})}
function plannerValues(){const travelers=Math.max(1,+$('#travelers').value||1),days=Math.max(1,+$('#days').value||1),airfare=Math.max(0,+$('#airfare').value||0),daily=Math.max(0,+$('#daily').value||0),stay=Math.max(0,+$('#stayCost').value||0),local=Math.max(0,+$('#localCost').value||0);return{travelers,days,airfare,daily,stay,local,total:airfare*travelers+daily*travelers*days+stay*Math.max(0,days-1)+local}}
function originName(){const s=$('#origin');return s.value==='other'?($('#customOrigin').value.trim()||'Other location'):s.options[s.selectedIndex].text}
function updatePlannerSummary(){const v=plannerValues(),flow=areaFlows[state.area]||areaFlows.north;$('#summaryDays').textContent=v.days+' DAY'+(v.days===1?'':'S');$('#summaryOrigin').textContent=originName();$('#summaryArea').textContent=zones[state.area].title;$('#budgetTotal').textContent=money(v.total);$('#budgetBreakdown').innerHTML=`<div class="budget-line"><span>Airfare</span><b>${money(v.airfare*v.travelers)}</b></div><div class="budget-line"><span>Daily allowance</span><b>${money(v.daily*v.travelers*v.days)}</b></div><div class="budget-line"><span>Accommodation</span><b>${money(v.stay*Math.max(0,v.days-1))}</b></div><div class="budget-line"><span>Local tours/transport</span><b>${money(v.local)}</b></div>`;$('#itineraryPreview').innerHTML=Array.from({length:Math.min(v.days,4)},(_,i)=>`<div><b>DAY ${i+1}</b><span>${flow[i]||'Flexible / free day'}</span></div>`).join('');$('#reviewRoute').innerHTML=`<div><i class="bi bi-geo"></i><span><small>FROM</small><b>${safe(originName())}</b></span></div><div><i class="bi bi-airplane"></i><span><small>ARRIVAL</small><b>Basco Airport</b></span></div><div><i class="bi bi-compass"></i><span><small>MAIN FOCUS</small><b>${zones[state.area].title}</b></span></div><div><i class="bi bi-wallet2"></i><span><small>WORKING BUDGET</small><b>${money(v.total)}</b></span></div>`}
function setPlannerStep(n){state.plannerStep=Math.max(1,Math.min(4,n));$$('.planner-pane').forEach(p=>p.classList.toggle('active',+p.dataset.pane===state.plannerStep));$$('.planner-step').forEach(b=>{const x=+b.dataset.step;b.classList.toggle('active',x===state.plannerStep);b.classList.toggle('done',x<state.plannerStep)});$('#plannerBack').style.visibility=state.plannerStep===1?'hidden':'visible';$('#plannerNext').style.display=state.plannerStep===4?'none':'inline-flex';updatePlannerSummary()}
function savePlan(){
 const v=plannerValues();
 const plan={origin:originName(),area:state.area,...v};
 localStorage.setItem(STORE.plan,JSON.stringify(plan));
 // A saved plan must immediately become a usable itinerary, not just planner metadata.
 // Rebuild only planner-generated day outlines so manually added/saved activities stay intact.
 const flow=areaFlows[state.area]||areaFlows.north;
 const manual=schedule.filter(x=>!x.planGenerated);
 const generated=Array.from({length:v.days},(_,i)=>({
  uid:`plan-${i+1}`,
  sourceId:`saved-plan-day-${i+1}`,
  type:'plan',
  planGenerated:true,
  name:flow[i]||'Flexible / free day',
  area:i===0?'Basco':(zones[state.area]?.title||'Batanes'),
  day:i+1,
  start:i===0?'14:00':'08:00',
  end:i===0?'17:00':'17:00',
  cost:0,
  notes:i===0?'Saved from Trip Planner · Keep arrival day light and flexible.':'Saved from Trip Planner · Edit this day to add exact stops, times and costs.'
 }));
 schedule=[...generated,...manual].sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));
 localStorage.setItem(STORE.schedule,JSON.stringify(schedule));
 renderScheduleDayOptions();
 renderItinerary();
 renderPlanningTable();
 updateSavedCount();
 showToast('Plan saved to My Trip');
 setTimeout(()=>navigate('itinerary'),250)
}
function openScheduler(item,editId=null){state.modalItem=item;state.editingId=editId;renderScheduleDayOptions();const existing=editId?schedule.find(x=>x.uid===editId):null;$('#scheduleTitle').textContent=existing?'Edit itinerary item':(item.name||'Custom activity');$('#scheduleSub').textContent=item.area||item.type||'Custom activity';$('#scheduleNameWrap').style.display=(item.type==='custom'||existing?.type==='custom')?'block':'none';$('#scheduleName').value=existing?.name||item.name||'';$('#scheduleDay').value=existing?.day||1;$('#scheduleStart').value=existing?.start||'09:00';$('#scheduleEnd').value=existing?.end||'10:30';$('#scheduleCost').value=existing?.cost||0;$('#scheduleNotes').value=existing?.notes||'';$('#scheduleSave').innerHTML=existing?'Save changes <i class="bi bi-check2"></i>':'Add to itinerary <i class="bi bi-arrow-right"></i>';$('#scheduleModal').classList.add('open');checkOverlap()}
function renderScheduleDayOptions(){const opts=Array.from({length:daysCount()},(_,i)=>`<option value="${i+1}">Day ${i+1}</option>`).join('');$('#scheduleDay').innerHTML=opts;$('#memoryDay').innerHTML='<option value="">Unassigned</option>'+opts}
function checkOverlap(){const d=+$('#scheduleDay').value,s=$('#scheduleStart').value,e=$('#scheduleEnd').value;const clash=schedule.find(x=>x.uid!==state.editingId&&x.day===d&&s<x.end&&e>x.start);$('#overlapWarning').innerHTML=clash?`<i class="bi bi-exclamation-triangle"></i> This overlaps with <b>${safe(clash.name)}</b>. You can still save it.`:''}
function saveScheduled(){const item=state.modalItem||{name:'Custom activity',area:'Personal'};const data={uid:state.editingId||crypto.randomUUID?.()||String(Date.now()),sourceId:item.id||null,type:item.type||'custom',name:(item.type==='custom'?($('#scheduleName').value.trim()||'Custom activity'):item.name||'Custom activity'),area:item.area||'Personal',lat:item.lat,lng:item.lng,day:+$('#scheduleDay').value,start:$('#scheduleStart').value,end:$('#scheduleEnd').value,cost:+$('#scheduleCost').value||0,notes:$('#scheduleNotes').value.trim()};if(state.editingId){schedule=schedule.map(x=>x.uid===state.editingId?data:x)}else schedule.push(data);schedule.sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));localStorage.setItem(STORE.schedule,JSON.stringify(schedule));$('#scheduleModal').classList.remove('open');renderItinerary();renderPlanningTable();updateSavedCount();showToast(state.editingId?'Itinerary updated':'Added to itinerary');state.editingId=null}
function renderItinerary(){const days=daysCount(),flow=areaFlows[getPlan()?.area||state.area]||areaFlows.north;$('#dayTimeline').innerHTML=Array.from({length:days},(_,i)=>{const items=schedule.filter(x=>x.day===i+1);return `<article class="day-card"><div class="day-no"><small>DAY</small><b>${String(i+1).padStart(2,'0')}</b></div><div class="day-content"><h4>${flow[i]||'Flexible island day'}</h4><p>${i===0?'Keep arrival day light and flexible.':'Edit times freely and leave room for weather.'}</p><div class="scheduled-list">${items.length?items.map(x=>`<div class="scheduled-item"><time>${x.start}</time><div><b>${safe(x.name)}</b><span>${safe(x.area)}${x.notes?' · '+safe(x.notes):''}</span></div><small>${x.cost?money(x.cost):'—'}</small><button data-edit-schedule="${x.uid}" aria-label="Edit"><i class="bi bi-pencil"></i></button><button data-remove-schedule="${x.uid}" aria-label="Remove"><i class="bi bi-x"></i></button></div>`).join(''):'<span class="day-empty">No activities yet. Add from Discover or create your own.</span>'}</div></div></article>`}).join('');$('#savedItems').innerHTML=schedule.slice(0,8).map(x=>`<div class="saved-item"><div><small>DAY ${x.day} · ${x.start}</small><b>${safe(x.name)}</b></div><button data-edit-schedule="${x.uid}"><i class="bi bi-pencil"></i></button></div>`).join('');$('#savedHint').style.display=schedule.length?'none':'block';$$('[data-edit-schedule]').forEach(b=>b.onclick=()=>{const x=schedule.find(v=>v.uid===b.dataset.editSchedule);openScheduler(x,x.uid)});$$('[data-remove-schedule]').forEach(b=>b.onclick=()=>{schedule=schedule.filter(x=>x.uid!==b.dataset.removeSchedule);localStorage.setItem(STORE.schedule,JSON.stringify(schedule));renderItinerary();renderPlanningTable();updateSavedCount()});renderPlanningTable()}
function renderPlanningTable(){
 const body=$('#planningTableBody'); if(!body)return;
 if(!schedule.length){body.innerHTML=`<tr><td>Day 1</td><td>Morning</td><td><b>North Batan loop</b><small>Basco · Naidi · Valugan · Vayang</small></td><td>North Batan</td><td>Enter current quote</td></tr><tr><td>Day 2</td><td>Full day</td><td><b>South Batan loop</b><small>Mahatao · Ivana · Uyugan</small></td><td>South Batan</td><td>Enter current quote</td></tr><tr><td>Day 3</td><td>Full day</td><td><b>Sabtang day trip</b><small>Weather-dependent sea crossing</small></td><td>Sabtang</td><td>Enter current quote</td></tr>`;return}
 const sorted=[...schedule].sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));
 body.innerHTML=sorted.map(x=>`<tr><td><span class="badge text-bg-light">Day ${x.day}</span></td><td>${safe(x.start)}–${safe(x.end)}</td><td><b>${safe(x.name)}</b><small>${safe(x.notes||'Scheduled in My Trip')}</small></td><td>${safe(x.area||'Custom')}</td><td>${money(x.cost)}</td></tr>`).join('')
}
function updateSavedCount(){$('#savedCount').textContent=schedule.length}
function renderGallery(filter='all'){$('#galleryMosaic').innerHTML=gallery.filter(x=>filter==='all'||x[1]===filter).map(x=>`<figure class="gallery-item"><img src="${x[0]}" class="img-fluid" alt="${x[2]}"><figcaption class="gallery-caption">${x[2]}</figcaption></figure>`).join('')}
function renderMemories(){const grid=$('#memoryGrid');if(!memories.length){grid.innerHTML=`<div class="story-empty"><div class="story-polaroids"><figure><img src="${zones.north.places[2].img}" alt="Batanes inspiration"></figure><figure><img src="${zones.sabtang.places[0].img}" alt="Batanes inspiration"></figure><figure><img src="${zones.south.places[0].img}" alt="Batanes inspiration"></figure></div><h4>Your story starts with one moment.</h4><p>Add a photo and connect it to the day or place you visited.</p><label class="btn-main dark-btn">Add your first memory<input type="file" accept="image/*" data-empty-upload hidden></label></div>`;const u=$('[data-empty-upload]');if(u)u.onchange=e=>prepareMemory(e.target.files[0]);return}grid.innerHTML=memories.map((m,i)=>`<article class="story-card ${i%3===0?'wide':''}"><img src="${m.src}" alt="Travel memory photo"><div><small>${m.day?'DAY '+m.day+' · ':''}${safe(m.place||'BATANES')}</small><p>“${safe(m.note||'A moment from Batanes.')}”</p><button data-delete-memory="${i}"><i class="bi bi-trash3"></i></button></div></article>`).join('');$$('[data-delete-memory]').forEach(b=>b.onclick=()=>{memories.splice(+b.dataset.deleteMemory,1);localStorage.setItem(STORE.memories,JSON.stringify(memories));renderMemories()})}
function prepareMemory(file){if(!file||!file.type.startsWith('image/'))return;const r=new FileReader();r.onload=()=>{state.pendingMemory=r.result;$('#memoryPreview').src=r.result;renderScheduleDayOptions();$('#memoryPlace').value='';$('#memoryNote').value='';$('#memoryModal').classList.add('open')};r.readAsDataURL(file)}
function saveMemory(){if(!state.pendingMemory)return;memories.push({src:state.pendingMemory,place:$('#memoryPlace').value.trim(),day:+$('#memoryDay').value||null,note:$('#memoryNote').value.trim()});try{localStorage.setItem(STORE.memories,JSON.stringify(memories))}catch{memories.pop();showToast('Browser storage is full');return}state.pendingMemory=null;$('#memoryModal').classList.remove('open');renderMemories();showToast('Memory saved to your story')}
function openTripMap(){if(!schedule.some(x=>x.lat))return showToast('Add mapped destinations first');$('#tripMapModal').classList.add('open');setTimeout(()=>{if(tripMap)tripMap.remove();tripMap=L.map('tripMap').setView([20.45,121.95],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(tripMap);const pts=schedule.filter(x=>x.lat);pts.forEach((x,i)=>L.marker([x.lat,x.lng]).addTo(tripMap).bindPopup(`${i+1}. Day ${x.day} · ${safe(x.name)}`));if(pts.length>1)L.polyline(pts.map(x=>[x.lat,x.lng]),{dashArray:'6 8'}).addTo(tripMap);},100)}

function renderCollagePicker(){
 const picker=$('#collagePicker');
 if(!picker)return;
 if(memories.length<2){picker.innerHTML='<p class="small text-muted mb-0">Add at least two memories to create a collage.</p>';return}
 picker.innerHTML=memories.map((m,i)=>`<label class="collage-pick"><input type="checkbox" value="${i}" ${i<Math.min(4,memories.length)?'checked':''}><img src="${m.src}" alt="Memory ${i+1}"><span>${safe(m.place||'Batanes')}</span></label>`).join('');
 $$('#collagePicker input').forEach(x=>x.onchange=renderCollagePreview);
}
function selectedCollageMemories(){return $$('#collagePicker input:checked').slice(0,6).map(x=>memories[+x.value]).filter(Boolean)}
function renderCollagePreview(){
 const canvas=$('#collageCanvas'); if(!canvas)return;
 const format=$('#collageFormat')?.value||'post'; const dims=format==='story'?[1080,1920]:format==='landscape'?[1600,900]:[1080,1350];
 canvas.width=dims[0]; canvas.height=dims[1]; const ctx=canvas.getContext('2d');
 ctx.fillStyle='#F6E3D6';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#17383A';ctx.font='700 54px Manrope, sans-serif';ctx.fillText($('#collageHeading')?.value||'BATANES MEMORIES',70,90);ctx.font='28px DM Sans, sans-serif';ctx.fillText($('#collageSubtitle')?.value||'Where the wind led us.',70,135);
 const items=selectedCollageMemories(); if(!items.length){ctx.font='28px DM Sans, sans-serif';ctx.fillText('Select memories to preview your collage.',70,220);return}
 const layout=$('#collageLayout')?.value||'grid'; const top=190, gap=18, W=canvas.width-140, H=canvas.height-top-80;
 const boxes=[];
 if(layout==='film'){const h=(H-gap*(items.length-1))/items.length;items.forEach((_,i)=>boxes.push([70,top+i*(h+gap),W,h]));}
 else if(layout==='postcard'){items.forEach((_,i)=>{const cols=2, w=(W-gap)/2,h=(H-gap)/2;boxes.push([70+(i%2)*(w+gap),top+(Math.floor(i/2)%2)*(h+gap),w,h])})}
 else {const cols=items.length<=2?1:2, rows=Math.ceil(items.length/cols),w=(W-gap*(cols-1))/cols,h=(H-gap*(rows-1))/rows;items.forEach((_,i)=>boxes.push([70+(i%cols)*(w+gap),top+Math.floor(i/cols)*(h+gap),w,h]))}
 items.forEach((m,i)=>{const img=new Image();img.onload=()=>{const [x,y,w,h]=boxes[i];const r=Math.max(w/img.width,h/img.height),sw=w/r,sh=h/r,sx=(img.width-sw)/2,sy=(img.height-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);ctx.fillStyle='rgba(23,56,58,.82)';ctx.fillRect(x,y+h-46,w,46);ctx.fillStyle='#fff';ctx.font='20px DM Sans, sans-serif';ctx.fillText((m.day?'DAY '+m.day+' · ':'')+(m.place||'BATANES'),x+16,y+h-17)};img.src=m.src})
}
function openCollageStudio(){
 renderCollagePicker(); renderCollagePreview(); bootstrap.Modal.getOrCreateInstance($('#collageModal')).show();
}
function downloadCollage(){
 renderCollagePreview(); setTimeout(()=>{const a=document.createElement('a');a.download='my-batanes-collage.png';a.href=$('#collageCanvas').toDataURL('image/png');a.click()},350)
}

function bind(){
 $$('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
 $('#mapToggle').onclick=openMap;$('#mapClose').onclick=()=>$('#mapDrawer').classList.remove('open');
 $$('[data-guide-card]').forEach(b=>b.onclick=()=>openGuideDetail(b.dataset.guideCard));
 $('#experiencePrevPhoto').onclick=()=>moveExperiencePhoto(-1);$('#experienceNextPhoto').onclick=()=>moveExperiencePhoto(1);$('#nextExperience').onclick=()=>{state.experience=(state.experience+1)%experiences.length;state.experiencePhoto=0;renderExperience()};$('#saveExperience').onclick=()=>openScheduler({id:'exp-'+state.experience,name:experiences[state.experience].title,area:'Experience',type:'experience'});
 $('#detailClose').onclick=()=>$('#detailModal').classList.remove('open');$('#detailSave').onclick=()=>{if(state.modalItem){$('#detailModal').classList.remove('open');openScheduler(state.modalItem)}};
 $('#scheduleClose').onclick=()=>$('#scheduleModal').classList.remove('open');$('#scheduleSave').onclick=saveScheduled;['scheduleDay','scheduleStart','scheduleEnd'].forEach(id=>$('#'+id).oninput=checkOverlap);
 $('#origin').onchange=()=>{$('#customOriginWrap').classList.toggle('d-none',$('#origin').value!=='other');updatePlannerSummary()};['customOrigin','travelers','days','airfare','daily','stayCost','localCost'].forEach(id=>$('#'+id).addEventListener('input',()=>{updatePlannerSummary();if(id==='days')renderScheduleDayOptions()}));$('#plannerNext').onclick=()=>setPlannerStep(state.plannerStep+1);$('#plannerBack').onclick=()=>setPlannerStep(state.plannerStep-1);$$('.planner-step').forEach(b=>b.onclick=()=>setPlannerStep(+b.dataset.step));$('#buildTrip').onclick=savePlan;
 $('#addCustom').onclick=()=>openScheduler({id:'custom-'+Date.now(),name:'Custom activity',area:'Personal',type:'custom'});$('#tripMapToggle').onclick=openTripMap;$('#tripMapClose').onclick=()=>$('#tripMapModal').classList.remove('open');$('#addDay').onclick=()=>{const p=getPlan()||{days:4,area:'north'};p.days=(p.days||4)+1;localStorage.setItem(STORE.plan,JSON.stringify(p));renderScheduleDayOptions();renderItinerary();showToast('Added one day')};$('#clearItinerary').onclick=()=>{if(confirm('Clear your itinerary?')){schedule=[];localStorage.removeItem(STORE.schedule);renderItinerary();updateSavedCount();showToast('Itinerary cleared')}};
 $$('.gallery-filter button').forEach(b=>b.onclick=()=>{$$('.gallery-filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGallery(b.dataset.filter)});$('#memoryUpload').onchange=e=>prepareMemory(e.target.files[0]);$('#memoryClose').onclick=()=>$('#memoryModal').classList.remove('open');$('#memorySave').onclick=saveMemory;$('#openCollage').onclick=openCollageStudio;$('#downloadCollage').onclick=downloadCollage;['collageHeading','collageSubtitle','collageLayout','collageFormat'].forEach(id=>$('#'+id).oninput=renderCollagePreview);
 $('#menuBtn').onclick=()=>$('#mobileMenu').classList.add('open');$('#menuClose').onclick=()=>$('#mobileMenu').classList.remove('open');const navs=['home','discover','experiences','guide','plan','gallery','itinerary'];$('.mobile-menu nav').innerHTML=navs.map(n=>`<button data-mobile-view="${n}">${n==='guide'?'Travel Guide':n[0].toUpperCase()+n.slice(1)}</button>`).join('');$$('[data-mobile-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.mobileView));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.detail-modal,.schedule-modal,.trip-map-modal,.memory-modal,.mobile-menu,.map-drawer').forEach(x=>x.classList.remove('open'))})
}
function init(){renderHero();restartHero();renderHomeExtras();renderZone();renderExperience();renderGuide();renderAreaChoices();updatePlannerSummary();renderScheduleDayOptions();renderItinerary();renderGallery();renderMemories();updateSavedCount();bind();initMap();$('#siteHeader').classList.remove('light')}
document.addEventListener('DOMContentLoaded',init);
